### ISSUE TITLE
rotating_file_sink: failed renaming

### ISSUE THREAD

**Issue by Gr1m5ky** [WopsS/RED4ext#32]
<This only started a day or two ago, and I'm not sure what's causing it. 
![Cyberpunk RED4Ext Error](https://github.com/WopsS/RED4ext/assets/116129040/3f4cb996-721d-4371-9059-dbc78d52ce34)
Steps to fix:
I've uninstalled all of my mods, and only reinstalled CET and RED4Ext. and got the same error.

Other:
I've altered my save using CyberCAT save editor.
The game now crashes before getting to the intro.

**Comment by extract** [comment]
I'm guessing this is related to that your red4ext.log files don't have the correct permissions. Make sure it's not read only. Most likely not a bug with red4ext per se, but with the directory settings.

**Comment by MomoTheTanuki** [comment]
Make sure the game is not launching twice. This happened to me when CP2077 launched twice, where one instance locked red4ext.log, and the second instance of the game couldn't rename the file.

**Comment by poirierlouis** [comment]
If you run the game with elevated privilege (as Administrator), it will creates these log files with elevated privileges. If you run the game again without elevated privilege, this error will show because the game (and RED4ext) will not be granted the access to manipulate the log files. You can either remove the log file and restart the game, or you can start the game as Administrator.

**Comment by WopsS** [comment]
As some people said above, this can be because:

- You are having 2 instances of Cyberpunk 2077 running as @MomoTheTanuki; or
- You need to run the game with admin privileges. As @poirierlouis said.

Were you able to solve it?

**Comment by pop1986** [comment]
Other "fixes"
"Good news guys, I'm sure many of you have been plagued by this problem:
you download the latest version of red4ext and related mods and install them in a clean game, but can't get into the game, and red4ext isn't generating logs at all.
it means that there's something preventing these dlls from being injected into the game process.
The solution is: open the cyberpunk2077/red4ext folder, copy red4ext.dll to the cyberpunk2077/bin/x64/plugins folder and change the extension to .asi, then you can play happily, no more crashes, enjoy!"
Credits to Muxterr

Did not work for me.

"I got the same thing, and this error goes away when I install red4ext in the end of all my mods."
Credits to UMR

Did not work for me.

"Hello

I have fixed it by deleting mod_settings folder located in Cyberpunk 2077\red4ext\plugins
Folder was stuck on old version of RED4text

Give it a try (same problem with 1.18.0) "
Credits to Omen7

Did not work for me. Not even sure if related.

Part of my issue: I can not remove the "read only" flag at the folder. I have given myself full rights on C: working throu 2 tutorials for pwershell and using folder options. Despite having all permissions (right click/properities/Security/permissions) on all accounts, the read only flag is constantly being reset. Win10 issue?? Any idea how to fix this?
Running game as administrator and such makes no difference. Game crashes with any red mod installed.

**Comment by pop1986** [comment]
2 and a half months in. Shortly after a major update released and people want to make new play throughs. Issue still persists. No actual fixes in sight. Luckely red4ext is not important for anything to run, otherwise this would be a major fuck up for some people.

**Comment by effs** [comment]
@pop1986 You are understandably frustrated being affected by some rare issue, but that is no excuse to behave this way. You are completely out of line. WopsS along with a handful of other incredibly skilled people have volunteered a ton of their valuable time to create something for the benefit of hundreds of thousands of modders, including having to crunch to fix it every single time the game is updated, and I expect a whole lot better from the community than this sort of comment.

**Comment by WopsS** [comment]
Is your issue related to the log files?

If so, the solution was described above, see https://github.com/WopsS/RED4ext/issues/32#issuecomment-1751665098.

Nothing more can be done about this.

**Comment by WSSDude** [comment]
Well, you could put the log in some other place as many peeps prolly just install things to program files...

But I believe this is an issue pretty much with every native mod for pretty much any game... As noone really puts logs outside of where they have the asi/dll/sth usually... So somewhere in the game folder...

**Comment by WSSDude** [comment]
Multiple instances can be handled via mutex, we do so with CET.

**Comment by WSSDude** [comment]
So sth can be done but is it worth it? Guess multiple instances at least can be resolved easily via the named mutex trick CET uses.

**Comment by WopsS** [comment]
> So sth can be done but is it worth it? Guess multiple instances at least can be resolved easily via the named mutex trick CET uses.

That's what I'm thinking. Is it worth it?
The muted trick was implemented before but I removed it at some point because I didn't see the use case.

Another case would be to not rotate the file and just append or truncate ir.

**Comment by poirierlouis** [comment]
> > So sth can be done but is it worth it? Guess multiple instances at least can be resolved easily via the named mutex trick CET uses.
> 
> That's what I'm thinking. Is it worth it? The muted trick was implemented before but I removed it at some point because I didn't see the use case.

I was thinking about this issue to run multiple instances. What about naming log files with a PID? I don't know if it can be accessed when running from a DLL on Windows, but it would be unique per instance and no need to bother with mutex... Just appending PID could be enough and I think it would still be possible to keep log rotation (e.g. `red4ext.[ROTATION].[PID].log`).

I might look into this soon.

> 
> Another case would be to not rotate the file and just append or truncate it.

I guess truncate would be better to prevent file to grow too much... Well, it can already be disabled in the [options](https://docs.red4ext.com/getting-started/configuration).

**Comment by pop1986** [comment]
@effs Understandable frustrated or completely out of line? At least get your own head straight before you try to make others feel bad for modders doing modding or users talk about issues or whatever it is you are getting at. It is not like I haven't tried to solve the issue myself, posting a long ass report right above the comment that caused your immeasurable disappointment in the community.

@WopsS Game is installed in C:\Cyberpunk 2077\
As I wrote above ... running in admin mode is very basic and one of many things that I have tried to solve this.
One thing I have not done yet is to install the game somewhere else, because I kinda gave up on this. Would this actually help? If so, when not into Program Files (x86), where should i install it for best chances of success?

**Comment by poirierlouis** [comment]
> @WopsS Game is installed in C:\Cyberpunk 2077 As I wrote above ... running in admin mode is very basic and one of many things that I have tried to solve this. One thing I have not done yet is to install the game somewhere else, because I kinda gave up on this (re-installed so many times already that i feel my SSD melting). Would this actually help? If so, when not into Program Files (x86), where should i install it for best chances of success?
> 
> Edit Some other things that i have tried: Starting windows from admin account, set rights from there, start as admin from there, deactivate antivirus, deactivating windows folder protection (Or rather checking that it actually is deactivated), installing the newest version, installing 2.1 version, installing 2.2 version. Nothing helped.

Version 2.2? Nevertheless, according to your previous post, issue arises due to read only flag set and that you're unable to unset it. So, this seems to be a Windows problem not a direct RED4ext problem. Changing game's directory should be irrelevant (except maybe, if your system setup is unique in some way).

After a search I came up with this article on Microsoft official forum which propose a [solution](https://answers.microsoft.com/en-us/windows/forum/all/cannot-change-filesfolders-from-read-only/fabf4d26-972a-4881-9f0e-38f788fe1f43). If you haven't already, please try it and let's us know if it worked.

**Comment by WopsS** [comment]
> > > So sth can be done but is it worth it? Guess multiple instances at least can be resolved easily via the named mutex trick CET uses.
> > 
> > That's what I'm thinking. Is it worth it? The muted trick was implemented before but I removed it at some point because I didn't see the use case.
> 
> I was thinking about this issue to run multiple instances. What about naming log files with a PID? ~~I don't know if it can be accessed when running from a DLL on Windows~~, but it would be unique per instance and no need to bother with mutex... Just appending PID could be enough and I think it would still be possible to keep log rotation (e.g. `red4ext.[ROTATION].[PID].log`).
> 
> ~~I might look into this soon.~~ [GetCurrentProcessId()](https://learn.microsoft.com/en-gb/windows/win32/api/processthreadsapi/nf-processthreadsapi-getcurrentprocessid?redirectedfrom=MSDN) should do it when DLL is attached.
> 
> > 
> > Another case would be to not rotate the file and just append or truncate it.
> 
> I guess truncate would be better to prevent file to grow too much...

I was considering this approach, but then you have to write your own logger sink that keeps track of which file is being used and so on.

I think the most simple solution is to not rotate the files and set the maximum size of the log file.

**Comment by effs** [comment]
> I think the most simple solution is to not rotate the files and set the maximum size of the log file.

You do have a few options for log management if it really is just file access or incomplete cleanup that's the issue, something like `red4ext.<pid|yymmddhhmm>.log` being the safest… I don't think running out of disk space is a major concern but you could also attempt to delete >N old log files on startup and ignore the error if it fails. The ROI doesn't seem to be there beyond avoiding unnecessary failure and ensuring that current and latest logs are preserved.

**Comment by pop1986** [comment]
@poirierlouis Microsoft support said that the read only flag has nothing to do with permissions and should be ignored. The flag is for something something internal reason for windows folder blah. I dunno. But it has nothing to do with Folder permissions. Those are all fully set up, thanks to tutorials like this. In other words: It is NOT a windows issue and has nothing to do with windows permissions. Otherwise, running as Admin and all that would actually solve the issue. Which (as I described) doesn't. The problem lies somewhere else.

**Comment by lissensp** [comment]
Hi, just want to say that I encountered the same error because the log file was open in glogg, this tool puts some kind of lock on the files it is watching, have not encountered this behaviour with notepad++,  baretail / baregrep or VS code

for me a nice to have would be to just be able to disable log rotation in the config if needed

**Comment by maximegmd** [comment]
This should already be fixed with the PR I made last week.

**Comment by GH0STP4WZ** [comment]
Hi, Not reopening this cuz it could genuinely be user error, but I'm having this issue with 1.30.0
I believe it might be user error becuase I'm running the game under Wine on Linux, and so far, this seems like the most likely place I might find a solution. I'm running  the game through heroic with GE-Proton-Latest and the only launch argument I'm running is `WINEDLLOVERRIDES=winmm,version=n,b` 

I'm not entirely sure what else to do here.
